# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='midea_authenticated',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='midea_password',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='midea_user',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
