# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170619_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='midea_ssotoken',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
