# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mideauserprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MideaUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.CharField(default='default', max_length=100)),
                ('groupid', models.CharField(default='default', max_length=100)),
                ('weight', models.CharField(default='default', max_length=100)),
                ('title', models.CharField(default='default', max_length=100)),
            ],
        ),
    ]
