# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mideausergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(default='default', max_length=100)),
                ('cardName', models.CharField(default='default', max_length=100)),
            ],
        ),
    ]
