"""
Django settings for July project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys
import pymysql
pymysql.install_as_MySQLdb()
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-x6(4)k1l*%#bth#imz70+#(^o85#*+i09_%ah96&qivgq)_ug'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'pure_pagination',
    'admin',
    'blog',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'July.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # 处理静态文件
                'utils.content_processors.static_git',

            ],
        },
    },
]

WSGI_APPLICATION = 'July.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
    #    'ENGINE': 'django.db.backends.sqlite3',
    #    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #     'NAME': 'file/db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sampledb',
        'USER':'haisong',
        'PASSWORD':'haisong',
        'HOST':'mysql.haisong.svc',
        'PORT':'3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# 静态文件路径
STATIC_URL = 'http://haisome.gitee.io/blog/static/'
STATIC_GIT_URL = 'http://haisome.gitee.io/blog/static/'#'https://haisome.github.io/blog/static/'
#STATIC_URL = '/static/'
#STATIC_GIT_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# 文件上传
#MEDIA_URL = 'http://haisome.oschina.io/blog/media/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
#MEDIA_ROOT = 'file/media'
# 指定默认的用户表
AUTH_USER_MODEL = 'users.UserProfile'

# 发送邮件
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "forhaisome@gmail.com"
EMAIL_HOST_PASSWORD = "lwntkhvncmobyhbl"#应用密码
EMAIL_USE_TLS = True
EMAIL_FROM = "forhaisome@gmail.com"  # 发件人

# 分页
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 10,
    'MARGIN_PAGES_DISPLAYED': 2,
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}
#网页首页
HOME_PAGE_URL = "http://django-haisong.1d35.starter-us-east-1.openshiftapps.com"
#七牛
BUCKET_URL = 'http://oqeu1fg6y.bkt.clouddn.com/'
BUCKET_NAME = 'pythonanywhere'
ACCESS_KEY = 'rR79xTrIlWP9Nrdct8dDYk4zsI6WwDxja1MNriEw'
SECRET_KEY = '2jwgW8kqnsM-Vb_iNwyjTfmATNLmC07zINc7jCfE'
